version: '3.3'
services:
    mongo_project:
        image: mongo:4.2.5
    project_part2:
        build: .
        environment:
            WAIT_HOSTS: mongo:27017
        ports:
            - '8080:8080'